# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Underpass < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cjdenio/underpass/releases/download/v0.0.2/underpass_0.0.2_Darwin_arm64.tar.gz"
      sha256 "3f6e12820130a2a4a21d6eda42ebfcba597f4fdacaa226d4d6eb6ce6587fabaa"

      def install
        bin.install "underpass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cjdenio/underpass/releases/download/v0.0.2/underpass_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "3750ea214d5ddd9c51ade2ae0a82fc09a1c75514ea196d9c8bea755f44ce8962"

      def install
        bin.install "underpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cjdenio/underpass/releases/download/v0.0.2/underpass_0.0.2_Linux_arm64.tar.gz"
      sha256 "76cfee7478c1f5a8f80aeb29c30200accbc2f3f9b24d58c7835d75c2aa9a5a94"

      def install
        bin.install "underpass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cjdenio/underpass/releases/download/v0.0.2/underpass_0.0.2_Linux_x86_64.tar.gz"
      sha256 "ddb0399c7869c2690d4f88d6d15874c1e253b29349649410280bc292c457b008"

      def install
        bin.install "underpass"
      end
    end
  end
end
